In [1]:
import PIL.Image
import numpy as np

In [5]:
cimage = PIL.Image.open('chessc.png')

FileNotFoundError: [Errno 2] No such file or directory: 'chessc.png'

In [5]:
width, height = cimage.size

In [6]:
ncimage = np.array(cimage)

In [13]:
cropped = ncimage[np.ix_(range(0, height, 4), range(0, width, 4))]

In [11]:
ncimage.shape

(480, 640, 3)

In [15]:
cropped.shape

(120, 160, 3)

In [7]:
dimage = PIL.Image.open('chessd.png')

In [8]:
ndimage = np.array(dimage, dtype=np.uint16)

In [9]:
dimage.mode

'I'

In [51]:
def with_depth(ndi: np.ndarray, homo: bool = False):
    @np.vectorize
    def iter():
        for i, row in enumerate(ndi):
            xs = []
            for j, depth in enumerate(row):
                coord = [i, j, depth]
                if homo:
                    coord.append(1)
                xs.append(coord)
            yield xs
    return np.array(list(iter()))

In [10]:
def assoc_z_axis(ndi: np.ndarray, homo: bool=True):
    @np.vectorize
    def iter():
        ys = []
        for i, row in enumerate(ndi):
            xs = []
            for j, depth in enumerate(row):
                coord = [i, j, depth]
                if homo:
                    coord.append(1)
                xs.append(coord)
            ys.append(xs)
        return ys
    return np.array(iter())

In [160]:
def assoc_z_axis_c(ndi: np.ndarray):
    r, c = ndi.shape
    pts = np.array(np.meshgrid(range(r), range(c))).T.reshape(r, c, 2)
    return np.concatenate((pts, np.expand_dims(ndi, axis=2)), axis=2)

In [11]:
%time depths = with_depth(darray, True)

NameError: name 'with_depth' is not defined

In [15]:
%time depths = assoc_z_axis(ndimage, False)

CPU times: user 391 ms, sys: 43.3 ms, total: 434 ms
Wall time: 429 ms


In [162]:
%time assoc_z_axis_c(ndimage)

CPU times: user 9.02 ms, sys: 118 µs, total: 9.14 ms
Wall time: 7.41 ms


array([[[   0,    0,    0],
        [   0,    1,    0],
        [   0,    2,    0],
        ...,
        [   0,  637,    0],
        [   0,  638,    0],
        [   0,  639,    0]],

       [[   1,    0,    0],
        [   1,    1,    0],
        [   1,    2,    0],
        ...,
        [   1,  637,    0],
        [   1,  638,    0],
        [   1,  639,    0]],

       [[   2,    0,    0],
        [   2,    1,    0],
        [   2,    2,    0],
        ...,
        [   2,  637,    0],
        [   2,  638,    0],
        [   2,  639,    0]],

       ...,

       [[ 477,    0, 2639],
        [ 477,    1, 2659],
        [ 477,    2, 2659],
        ...,
        [ 477,  637,    0],
        [ 477,  638,    0],
        [ 477,  639,    0]],

       [[ 478,    0, 2599],
        [ 478,    1, 2619],
        [ 478,    2, 2659],
        ...,
        [ 478,  637,    0],
        [ 478,  638,    0],
        [ 478,  639,    0]],

       [[ 479,    0, 2619],
        [ 479,    1, 2619],
        [ 479,  

In [38]:
trans = np.loadtxt('chesst.txt')

In [39]:
trans

array([[ 0.99935108, -0.01557608,  0.03150894, -0.12323361],
       [ 0.00923751,  0.98130137,  0.19211653, -1.1206967 ],
       [-0.03391284, -0.19170459,  0.98083067, -0.98870575],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [43]:
darray = np.array(dimage)

In [53]:
np.dot(depths, trans)

array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00],
        [ 9.23750920e-03,  9.81301370e-01,  1.92116530e-01,
         -1.20696700e-01],
        [ 1.84750184e-02,  1.96260274e+00,  3.84233060e-01,
         -1.24139340e+00],
        ...,
        [ 5.88429336e+00,  6.25088973e+02,  1.22378230e+02,
         -7.12883798e+02],
        [ 5.89353087e+00,  6.26070274e+02,  1.22570346e+02,
         -7.14004495e+02],
        [ 5.90276838e+00,  6.27051575e+02,  1.22762463e+02,
         -7.15125191e+02]],

       [[ 9.99351080e-01, -1.55760840e-02,  3.15089410e-02,
          8.76766390e-01],
        [ 1.00858859e+00,  9.65725286e-01,  2.23625471e-01,
         -2.43930310e-01],
        [ 1.01782610e+00,  1.94702666e+00,  4.15742001e-01,
         -1.36462701e+00],
        ...,
        [ 6.88364444e+00,  6.25073397e+02,  1.22409739e+02,
         -7.13007032e+02],
        [ 6.89288195e+00,  6.26054698e+02,  1.22601855e+02,
         -7.14127728e+02],
        [ 6.902

In [1]:
from train import train_shitnet

ModuleNotFoundError: No module named 'torch'

In [37]:
sqdepths = np.insert(depths, 3, 1, axis=2)

In [38]:
sqdepths



array([[[   0,    0,    0,    1],
        [   0,    1,    0,    1],
        [   0,    2,    0,    1],
        ...,
        [   0,  637,    0,    1],
        [   0,  638,    0,    1],
        [   0,  639,    0,    1]],

       [[   1,    0,    0,    1],
        [   1,    1,    0,    1],
        [   1,    2,    0,    1],
        ...,
        [   1,  637,    0,    1],
        [   1,  638,    0,    1],
        [   1,  639,    0,    1]],

       [[   2,    0,    0,    1],
        [   2,    1,    0,    1],
        [   2,    2,    0,    1],
        ...,
        [   2,  637,    0,    1],
        [   2,  638,    0,    1],
        [   2,  639,    0,    1]],

       ...,

       [[ 477,    0, 2639,    1],
        [ 477,    1, 2659,    1],
        [ 477,    2, 2659,    1],
        ...,
        [ 477,  637,    0,    1],
        [ 477,  638,    0,    1],
        [ 477,  639,    0,    1]],

       [[ 478,    0, 2599,    1],
        [ 478,    1, 2619,    1],
        [ 478,    2, 2659,    1],
        .

In [39]:
np.insert(np.array([[[1, 2, 3], [3, 4, 5]]]), 3, 1, axis=2)


array([[[1, 2, 3, 1],
        [3, 4, 5, 1]]])

In [40]:
homo = np.array([[[2, 4, 2], [3, 9, 3]]])


In [70]:
np.delete(homo / homo[:, :, 2].T, 2, 2)

array([[[1., 2.],
        [1., 3.]]])

In [63]:
homo[:, :, 2].T

array([[2],
       [3]])

In [95]:
def to_nonke(ds):
    return np.delete(ds / np.expand_dims(ds[..., 3], axis=2), 3, 2)

In [96]:
to_nonke(sqdepths)

array([[[0.000e+00, 0.000e+00, 0.000e+00],
        [0.000e+00, 1.000e+00, 0.000e+00],
        [0.000e+00, 2.000e+00, 0.000e+00],
        ...,
        [0.000e+00, 6.370e+02, 0.000e+00],
        [0.000e+00, 6.380e+02, 0.000e+00],
        [0.000e+00, 6.390e+02, 0.000e+00]],

       [[1.000e+00, 0.000e+00, 0.000e+00],
        [1.000e+00, 1.000e+00, 0.000e+00],
        [1.000e+00, 2.000e+00, 0.000e+00],
        ...,
        [1.000e+00, 6.370e+02, 0.000e+00],
        [1.000e+00, 6.380e+02, 0.000e+00],
        [1.000e+00, 6.390e+02, 0.000e+00]],

       [[2.000e+00, 0.000e+00, 0.000e+00],
        [2.000e+00, 1.000e+00, 0.000e+00],
        [2.000e+00, 2.000e+00, 0.000e+00],
        ...,
        [2.000e+00, 6.370e+02, 0.000e+00],
        [2.000e+00, 6.380e+02, 0.000e+00],
        [2.000e+00, 6.390e+02, 0.000e+00]],

       ...,

       [[4.770e+02, 0.000e+00, 2.639e+03],
        [4.770e+02, 1.000e+00, 2.659e+03],
        [4.770e+02, 2.000e+00, 2.659e+03],
        ...,
        [4.770e+02, 6.370e

In [92]:
sqdepths / np.expand_dims(sqdepths[..., 3], axis=2)

array([[[0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00],
        [0.000e+00, 1.000e+00, 0.000e+00, 1.000e+00],
        [0.000e+00, 2.000e+00, 0.000e+00, 1.000e+00],
        ...,
        [0.000e+00, 6.370e+02, 0.000e+00, 1.000e+00],
        [0.000e+00, 6.380e+02, 0.000e+00, 1.000e+00],
        [0.000e+00, 6.390e+02, 0.000e+00, 1.000e+00]],

       [[1.000e+00, 0.000e+00, 0.000e+00, 1.000e+00],
        [1.000e+00, 1.000e+00, 0.000e+00, 1.000e+00],
        [1.000e+00, 2.000e+00, 0.000e+00, 1.000e+00],
        ...,
        [1.000e+00, 6.370e+02, 0.000e+00, 1.000e+00],
        [1.000e+00, 6.380e+02, 0.000e+00, 1.000e+00],
        [1.000e+00, 6.390e+02, 0.000e+00, 1.000e+00]],

       [[2.000e+00, 0.000e+00, 0.000e+00, 1.000e+00],
        [2.000e+00, 1.000e+00, 0.000e+00, 1.000e+00],
        [2.000e+00, 2.000e+00, 0.000e+00, 1.000e+00],
        ...,
        [2.000e+00, 6.370e+02, 0.000e+00, 1.000e+00],
        [2.000e+00, 6.380e+02, 0.000e+00, 1.000e+00],
        [2.000e+00, 6.390e+02, 0.000e+0

In [94]:
np.expand_dims(sqdepths[..., 3], axis=2).shape

(480, 640, 1)

In [97]:
sqdepths.shape


(480, 640, 4)

In [104]:
np.meshgrid([1, 2], [1, 2, 3])

[array([[1, 2],
        [1, 2],
        [1, 2]]),
 array([[1, 1],
        [2, 2],
        [3, 3]])]

In [106]:
import itertools as itt

In [127]:
%time np.array(np.meshgrid(range(2), range(2))).T.reshape(2, 2, 2)

CPU times: user 297 µs, sys: 51 µs, total: 348 µs
Wall time: 358 µs


array([[[0, 0],
        [0, 1]],

       [[1, 0],
        [1, 1]]])

CPU times: user 13 ms, sys: 77 µs, total: 13.1 ms
Wall time: 11.5 ms


array([[  0,   0],
       [  0,   1],
       [  0,   2],
       ...,
       [479, 637],
       [479, 638],
       [479, 639]])

In [147]:
np.expand_dims(ndimage, axis=2).shape

(480, 640, 1)

ModuleNotFoundError: No module named 'torchvision'